version: '3'
services:
  api-paas-postgres:
    container_name: api-paas-postgres
    build: .
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: postgres:epitech@postgres:5432
      PORT: 3000
      
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: epitech
      POSTGRES_DB: paas-project