version: '3'
services:
  api-paas-postgres:
    container_name: api-paas-postgres
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      REDIS_URL: ${REDIS_URL}
      PORT: ${PORT}

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis
    container_name: cache
    restart: always
    environment:
      REDIS_URL: redis://cache
    expose:
      - 6379